# Generated by Django 4.2.25 on 2025-10-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_eologin_eosignup_remove_eouser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosignup',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='eosignup',
            name='phone',
        ),
        migrations.AddField(
            model_name='eosignup',
            name='conpass',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='eosignup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eosignup',
            name='emp_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eosignup',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='eosignup',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
