# Generated by Django 4.2.25 on 2025-10-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_eosignup_full_name_remove_eosignup_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_admitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
