# Generated by Django 4.2.25 on 2025-12-05 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_signup_is_admitted_signup_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EOSignup',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='area',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='conpass',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_name',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
