# Generated by Django 4.2.25 on 2025-12-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_delete_eosignup_remove_supervisor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
