# Generated by Django 4.2.25 on 2025-12-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_post_description_post_deleted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eologin',
            old_name='emp_number',
            new_name='emp_id',
        ),
        migrations.AddField(
            model_name='eologin',
            name='name',
            field=models.CharField(default='EO202501', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eologin',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
