# Generated by Django 4.2.25 on 2025-12-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_emp_number_eologin_emp_id_eologin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(max_length=255),
        ),
    ]
