# Generated by Django 4.2.25 on 2025-12-11 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
