# Generated by Django 4.2.25 on 2025-12-11 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_request_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date_time',
        ),
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
