# Generated by Django 4.2.25 on 2025-12-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_request_date_time_request_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Public Safety', 'Public Safety'), ('Sanitation / Hygiene', 'Sanitation / Hygiene'), ('Road / Traffic Issues', 'Road / Traffic Issues'), ('Electricity / Water Supply', 'Electricity / Water Supply'), ('Government Services', 'Government Services'), ('Others', 'Others')], max_length=50),
        ),
    ]
