# Generated by Django 4.2.25 on 2025-12-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_complaint_status_task_verified_by_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('pending', 'Pending'), ('completed', 'Completed')], default='submitted', max_length=15),
        ),
    ]
