# Generated by Django 4.2.25 on 2025-12-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='name',
            new_name='supervisor_name',
        ),
    ]
