# Generated by Django 4.2.25 on 2025-12-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_rename_name_supervisor_supervisor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.supervisor'),
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.supervisor'),
        ),
    ]
