# Generated by Django 4.2.25 on 2025-12-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_complaint_supervisor_request_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='request',
            name='supervisor',
        ),
    ]
