# Generated by Django 4.2.25 on 2025-12-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_complaint_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='supervisor_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.supervisor'),
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.supervisor'),
        ),
    ]
