# Generated by Django 4.2.25 on 2025-12-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_complaint_supervisor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
    ]
