# Generated by Django 4.2.25 on 2025-12-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='supervisor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('pending', 'Pending'), ('completed', 'Completed')], default='submitted', max_length=15),
        ),
    ]
