# Generated by Django 4.2.25 on 2025-12-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_complaint_supervisor_name_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='area_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
