# Generated by Django 4.2.25 on 2025-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_complaint_area_name_request_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='area_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
