# Generated by Django 4.2.25 on 2025-12-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_complaint_area_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
    ]
