# Generated by Django 4.2.25 on 2025-12-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_request_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='area_name',
            field=models.CharField(default='Unknown Area', max_length=100),
        ),
    ]
